# USE SPECIFIC VERSION OF THE IMAGE
FROM node:16.17.0-alpine as builder

#DEFINE WORKIND DIRECTORY
WORKDIR /app

#COPY PACKAGES FILE
COPY ./package.json .
COPY ./yarn.lock .

#INSTALL DEPENDENCIES
RUN yarn install

#COPY REST OF THE FILES
COPY . .

#USED TO SETUP THE APIKEY OF TMDB
ARG TMDB_V3_API_KEY
ENV VITE_APP_TMDB_V3_API_KEY=${TMDB_V3_API_KEY}
ENV VITE_APP_API_ENDPOINT_URL="https://api.themoviedb.org/3"

#BUILD THE APPLICATION
RUN yarn build

#USE SPECIFIC VERSION OF THE NGINX IMAGE
FROM nginx:stable-alpine

#DEFINE WORKING DIRECTORY
WORKDIR /usr/share/nginx/html

#REMOVE PREVIOUS FILES FROM THE FOLDER
RUN rm -rf ./*

#COPY THE BUILD ARTIFACTS TO THE CURRENT WORKING DIRECTORY
COPY --from=builder /app/dist .

#EXPOSE PORT FOR THE CONTAINER
EXPOSE 80

#ENTRYPOINT
ENTRYPOINT ["nginx", "-g", "daemon off;"]
